<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GraphKit.Auth</AssemblyName>
    <RootNamespace>GraphKit.Auth</RootNamespace>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <IsPackable>false</IsPackable>
    <SelfContained>false</SelfContained>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GraphKit.Auth.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.82.1" />
    <ProjectReference Include="../GraphKit.Auth.Contracts/GraphKit.Auth.Contracts.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
