#
# Module manifest for module 'GraphKit'
#
# Generated by: Adam Gell
#
# Generated on: 8/15/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GraphKit.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '212637ed-2571-4e88-8df2-888a0c163ccd'

# Author of this module
Author = 'Adam Gell'

# Company or vendor of this module
CompanyName = 'Adam Gell'

# Copyright statement for this module
Copyright = '(c) Adam Gell. All rights reserved.'

# Description of the functionality provided by this module
Description = 'App-only, multi-tenant Microsoft Graph execution and analysis layer with explicit Intune and Entra operation semantics.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    # MSAL delivery vehicle only - Connect-MgGraph is never called. See the design spec.
    @{ ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '2.38.1' }
    @{ ModuleName = 'Microsoft.PowerShell.SecretManagement'; ModuleVersion = '1.1.2' }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# CopyPaths in build.yaml only PACKAGES the format file; it must also be
# REGISTERED here or default views silently never apply.
FormatsToProcess = @('Formats/GraphKit.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # No spaces permitted; PSGallery adds 'PSModule' itself.
        Tags = @(
            'Microsoft365'
            'MicrosoftGraph'
            'Graph'
            'Intune'
            'Entra'
            'EntraID'
            'MDM'
            'DeviceManagement'
            'MultiTenant'
            'AppOnly'
            'Automation'
            'Windows'
            'Linux'
            'MacOS'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/MIT'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
0.1.0 - first public release.

An app-only, multi-tenant Microsoft Graph execution layer for Intune and Entra. Its focus is
reliable request execution rather than breadth of coverage:

- Immutable per-tenant contexts. Tokens come from MSAL per context, never from a process-global
  connection, so parallel multi-tenant work cannot cross-contaminate.
- Four auth modes: certificate, client secret, managed identity, and a caller-supplied bearer.
  Credentials are referenced from SecretManagement, never stored in the profile.
- Semantics-aware retry that distinguishes a known failure from an indeterminate commit, and
  never blind-replays a write after an ambiguous response.
- Scoped throttling with AIMD admission control, keyed per cloud/tenant/client/resource so one
  throttled tenant does not stall the others.
- Operation behaviour is data, not code: each operation is a versioned descriptor declaring
  method, path, API version, paging, retry safety, permissions and cloud support.
- API version is a per-operation fact, not a global mode. Beta operations are separate,
  explicitly named, and declare why they are beta.

Requires PowerShell 7.4+. Depends on Microsoft.Graph.Authentication (as the MSAL delivery
vehicle only - Connect-MgGraph is never called) and Microsoft.PowerShell.SecretManagement.

Importing the module writes nothing to the error stream; a QA test asserts this, because a
non-terminating error on import is invisible to Should -Not -Throw.

This is an early release: the command surface is small and may change before 1.0.
'@

        # Prerelease string of this module
        Prerelease =  ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
