#
# Module manifest for module 'GraphKit'
#
# Generated by: Adam Gell
#
# Generated on: 8/15/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GraphKit.psm1'

# Version number of this module.
ModuleVersion = '0.1.2'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '212637ed-2571-4e88-8df2-888a0c163ccd'

# Author of this module
Author = 'Adam Gell'

# Company or vendor of this module
CompanyName = 'Adam Gell'

# Copyright statement for this module
Copyright = '(c) Adam Gell. All rights reserved.'

# Description of the functionality provided by this module
Description = 'App-only, multi-tenant Microsoft Graph execution and analysis layer with explicit Intune and Entra operation semantics.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    # MSAL delivery vehicle only - Connect-MgGraph is never called. See the design spec.
    @{ ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '2.38.1' }
    @{ ModuleName = 'Microsoft.PowerShell.SecretManagement'; ModuleVersion = '1.1.2' }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# CopyPaths in build.yaml only PACKAGES the format file; it must also be
# REGISTERED here or default views silently never apply.
FormatsToProcess = @('Formats/GraphKit.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # No spaces permitted; PSGallery adds 'PSModule' itself.
        Tags = @(
            'Microsoft365'
            'MicrosoftGraph'
            'Graph'
            'Intune'
            'Entra'
            'EntraID'
            'MDM'
            'DeviceManagement'
            'MultiTenant'
            'AppOnly'
            'Automation'
            'Windows'
            'Linux'
            'MacOS'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/MIT'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
0.1.2

Export hardening. Closes the last three findings from an external security review; all five are
now fixed.

Changed - these alter the output of Export-GraphResult:
- EVERY format now redacts secret-bearing properties. Previously only -As Json redacted, while
  -As Csv, -As Markdown and the VaultEvidence rows.json wrote rows raw.
- What is redacted is DECLARED by the operation, not inferred from property names. Descriptors
  name the properties their responses carry secrets in, and dotted paths are supported so a
  nested branch can be redacted without losing its siblings. Name-matching was measured against
  live responses and rejected: it redacts nine DeviceCompliancePolicy password-policy settings -
  configuration, not credentials - while missing scriptContent and Settings Catalog values
  entirely, producing an export that reads as sanitised and is not.
- CSV cells beginning = + - @ are prefixed with an apostrophe so a spreadsheet does not execute
  them. Strings only; negative numbers are untouched.
- Exporting rows without an envelope warns that no declaration is available, rather than
  redacting nothing silently.
- Get-GraphOperation returns a deep copy. It previously handed out the cached catalog objects,
  so a caller mutating one changed the descriptor every later operation in that session used -
  including its CredentialPolicy.

Added:
- Export-GraphResult -NoRedact writes rows exactly as the service returned them, for when the
  actual value is the point.
- Descriptors may declare SensitiveProperties, validated at load.

Operations declaring secrets today: DeviceManagementScript.List (scriptContent),
ServicePrincipal.List (passwordCredentials, keyCredentials) and
ConfigurationPolicySetting.ListBeta (settingInstance.groupSettingCollectionValue). A declaration
covers only what someone thought of - an operation returning a secret nobody declared is still
exported.

Fixed - a correctness bug in URI building:
- A PathTemplate that fixes a query option now extends it with '&' instead of a second '?'.
  Resolve-GraphUri always joined with '?', so a descriptor with a fixed option plus a
  caller-supplied one produced '?$expand=a?$filter=b'. That is not two options - the second '?'
  becomes part of the first option's value, so Graph answers 200 and IGNORES the filter,
  returning a complete collection that reads as a filtered one. Only Organization/GetMdmAuthority
  fixed an option before this release, and it was safe purely because it accepts no caller
  options at all.
- A caller-supplied option that the descriptor already fixes is now rejected by name, instead of
  being emitted twice for Graph to reject with an error naming the option rather than the
  descriptor responsible.

Added - four read-only beta descriptors, taking the catalog from 55 to 59:
- GroupPolicyConfiguration.ListBeta, GroupPolicyDefinitionValue.ListBeta and
  GroupPolicyPresentationValue.ListBeta - the three-level Administrative Template walk. The two
  child operations fix a load-bearing $expand in their path, because without it the rows are ids
  with no indication of which setting they configure: a 200 response that cannot be interpreted.
  GroupPolicyPresentationValue takes TWO path parameters, 'id' and 'definitionValueId'.
- ConfigurationPolicyAssignment.ListBeta - assignments for a Settings Catalog policy. This closes
  a silent gap: assignment descriptors existed for compliance policies, device configurations and
  mobile apps, so a reconciliation across policy types contributed nothing for Settings Catalog
  and still reported success.

All four are live-verified against POPULATED responses. The lab tenant's own administrative
templates turned out to be unpopulated shells - every one had zero definitionValues, which was
checked rather than assumed (a bogus parent id returns ResourceNotFound, so the endpoint does
distinguish missing from empty) - so a fixture policy was created there to exercise the walk
properly. Each descriptor header records the row shape that came back, and that the $expand is
load-bearing is measured rather than argued: the same requests without it return HTTP 200 and the
identical rows minus the 'definition' / 'presentation' keys.

Requires PowerShell 7.4+. 687 tests, 0 skipped, green on Windows, Linux and macOS across
PowerShell 7.4 and 7.6.
'@

        # Prerelease string of this module
        Prerelease =  ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # Both RequiredModules entries are satisfied from PSGallery, never from whatever
        # repository GraphKit itself is installed from. Without this declaration, PowerShellGet
        # resolving a local or private repository demands the dependencies exist in that SAME
        # repository and fails the install - which a consumer cannot fix from their side.
        # Reported with a live repro by a downstream consumer packaging against a local repo.
        ExternalModuleDependencies = @(
            'Microsoft.Graph.Authentication'
            'Microsoft.PowerShell.SecretManagement'
        )

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
